"use client";
import type { Metadata } from "next";
import { FloatingDock } from "@/components/ui/floating-dock";
import { IconHome, IconBrandLinkedin, IconBrandGithub, IconBrandTwitter, IconColorPicker } from "@tabler/icons-react"; // Example icons
import { ThemeProvider } from "next-themes";
import { useEffect } from "react";
import "../../styles/globals.css";
import { ToastProvider, ToastViewport } from "@/components/ui/toast";

const dockItems = [
  { title: "Home", icon: <IconHome />, href: "/" },
  { title: "Linked-in", icon: <IconBrandLinkedin />, href: "#" },
  { title: "GitHub", icon: <IconBrandGithub />, href: "#" },
  { title: "X", icon: <IconBrandTwitter />, href: "#" },
  { title: "Theme", icon: <IconColorPicker />, href: "#", id: "theme-switcher" },
];

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    document.documentElement.classList.add("dark");
  }, []);

  return (
    <html lang="en">
      <body>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <ToastProvider>
            {children}
            <FloatingDock items={dockItems} />
            <ToastViewport />
          </ToastProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
