export const siteMetadata = {
  title: "Vaibhav Kothari - Full Stack Developer & Software Engineer",
  description: "Experienced Full Stack Developer specializing in Next.js, React, TypeScript, and modern web technologies. Explore my portfolio featuring innovative projects, technical blog posts, open-source contributions, and professional experience in web development, software engineering, and UI/UX design.",
  siteUrl: "https://vaibhavkothari.vercel.app",
  alternateUrls: ["https://vaibhavkothari.me"],
  siteName: "Vaibhav Kothari",
  twitterHandle: "@VaibhavKotharii",
  author: {
    name: "Vaibhav Kothari",
    twitter: "https://twitter.com/VaibhavKotharii",
    linkedin: "https://www.linkedin.com/in/vaibhavkothari33",
    github: "https://github.com/vaibhavkothari33",
  },
  keywords: [
    "Vaibhav Kothari",
    "VaibhavKothari33",
    "Full Stack Developer",
    "Software Engineer",
    "Web Developer",
    "React Developer",
    "Next.js Developer",
    "TypeScript Expert",
    "JavaScript Developer",
    "Frontend Development",
    "Backend Development",
    "Node.js Developer",
    "UI/UX Design",
    "Web Applications",
    "RESTful APIs",
    "Database Design",
    "Cloud Computing",
    "Software Architecture",
    "Modern Web Development",
    "Open Source Contributor",
    "Tech Blogger",
    "System Design",
    "Performance Optimization",
    "Responsive Web Design",
    "Progressive Web Apps",
    "Code Quality",
    "Technical Leadership"
  ],
  creator: "Vaibhav Kothari",
  ogImage: "https://vaibhavkothari.vercel.app/og-image.png",
  themeColor: "#000000",
  category: "Technology",
  locale: "en-US",
  type: "website",
}; 