export const siteMetadata = {
  title: "Vaibhav Kothari - Full Stack Developer & Software Engineer",
  description: "Experienced Full Stack Developer specializing in Next.js, React, TypeScript, and modern web technologies. Browse my portfolio showcasing innovative projects, technical blog posts, and professional experience in web development and software engineering.",
  siteUrl: "https://vaibhavkothari.vercel.app",
  alternateUrls: ["https://vaibhavkothari.me"],
  siteName: "Vaibhav Kothari",
  twitterHandle: "@VaibhavKotharii",
  author: {
    name: "Vaibhav Kothari",
    twitter: "https://twitter.com/VaibhavKotharii",
    linkedin: "https://www.linkedin.com/in/vaibhavkothari33",
    github: "https://github.com/vaibhavkothari33",
  },
  keywords: [
    "Vaibhav Kothari",
    "VaibhavKothari33",
    "vaibhavKothari33",
    "Full Stack Developer",
    "Software Engineer",
    "Web Developer",
    "React Developer",
    "Next.js Developer",
    "TypeScript",
    "JavaScript",
    "Portfolio",
    "Blog",
    "Frontend Development",
    "Backend Development",
    "Node.js",
    "Web Applications",
    "UI/UX Design",
    "RESTful APIs",
    "Database Design",
    "Cloud Computing",
    "Software Architecture",
    "Modern Web Development"
  ],
  creator: "Vaibhav Kothari",
  ogImage: "https://vaibhavkothari.vercel.app/og-image.png",
  themeColor: "#000000",
  locale: "en-US",
  type: "website",
}; 